
name: CI

on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Test
        run: sbt test
        env:
          JVM_OPTS: -Xmx3200m
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/target/**/test-reports/*.xml"
      - name: Assembly
        run: sbt "set assembly / test := {}" assembly
        env:
          JVM_OPTS: -Xmx3200m
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "**/target/**/*.jar"
          name: assembly
          retention-days: 5